apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "postgres-db-setup.fullname" . }}
  labels:
    {{- include "postgres-db-setup.labels" . | nindent 4 }}
  annotations:
    {{ .Values.annotations | toYaml }}
spec:
  template:
    metadata:
      labels:
        {{- include "postgres-db-setup.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}