# Default values for postgres-db-setup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: keshavprasad/pg-db-create
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
restartPolicy: "OnFailure"

postgresDatabases: ["kong", "keycloak"]
postgresUser: ""
postgresPassword: ""
postgresHost: ""
postgresPort: ""

annotations:
  helm.sh/hook: pre-install, pre-upgrade